#!/usr/bin/env python3
"""
MCTD checkpoint scanner with mtime-based metadata cache and realpath deduplication.

Usage (run inside Docker):
    python3 ckpt_scanner.py <docker_outputs_path> <host_output_mount_dir> <target_obs_dim>

Output (stdout): one line per unique checkpoint matching target_obs_dim:
    name|host_path|mtime|epoch

Cache file: <docker_outputs_path>/ckpt_scan_cache.json
    { "<realpath_inside_docker>": {"obs_dim": int, "epoch": int, "mtime": int} }

Directory layout understood:
    NEW-STYLE (flat, preferred):
        <base>/<model_id>/model.ckpt          — symlink or real file
        e.g.  <base>/train_29d_j1_57ep_.../model.ckpt
              <base>/en1ddvu7/model.ckpt       (WandB download)

    OLD-STYLE (backward compat):
        <base>/downloaded/.../mctd_eval/<model_id>/model.ckpt

    RAW HYDRA OUTPUT (skipped — accessible only via symlinks above):
        <base>/YYYY-MM-DD/HH-MM-SS/checkpoints/model.ckpt

Deduplication:
    Multiple paths resolving to the same real file → one entry.
    Display name priority (lower = shown):
        0  new-style, not local_*   (train_29d_..., en1ddvu7, ...)
        1  new-style local_*        (auto-generated by eval.sh)
        2  old-style [eval] named   (backward compat named)
        3  old-style [eval] local_* (backward compat auto-generated)
"""
import re
import sys
import json
import torch
from pathlib import Path

_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def _name_priority(name: str) -> int:
    if name.startswith("[eval] local_"):
        return 3
    if name.startswith("[eval] "):
        return 2
    if name.startswith("local_"):
        return 1
    return 0


def main():
    if len(sys.argv) < 4:
        print(
            "Usage: ckpt_scanner.py <docker_outputs> <host_mount_dir> <target_dim>",
            file=sys.stderr,
        )
        sys.exit(1)

    docker_outputs = sys.argv[1]
    host_mount_dir = sys.argv[2]
    target_dim     = int(sys.argv[3])

    base       = Path(docker_outputs)
    cache_path = base / "ckpt_scan_cache.json"

    # ── Load metadata cache ──────────────────────────────────────────────────
    try:
        with open(cache_path) as f:
            cache: dict = json.load(f)
    except Exception:
        cache = {}

    cache_dirty = False

    # realpath_str → (best_name, host_path, mtime, epoch)
    best: dict[str, tuple] = {}

    for ckpt_path in sorted(base.rglob("model.ckpt")):
        try:
            rel   = ckpt_path.relative_to(base)
            parts = rel.parts  # relative parts from base

            # ── Classify path ────────────────────────────────────────────────
            if _DATE_RE.match(parts[0]):
                # Raw Hydra output: YYYY-MM-DD/HH-MM-SS/.../model.ckpt
                # Skip — these are shown only via their registered model_id symlink.
                continue

            if parts[0] == "downloaded":
                # Old-style: downloaded/.../mctd_eval/<model_id>/model.ckpt
                if "mctd_eval" not in parts:
                    continue
                idx      = list(parts).index("mctd_eval")
                model_id = parts[idx + 1]
                name     = f"[eval] {model_id}"
                host_path = host_mount_dir + str(ckpt_path)[len(docker_outputs):]
            elif len(parts) == 2 and parts[1] == "model.ckpt":
                # New-style flat: <model_id>/model.ckpt
                model_id  = parts[0]
                name      = model_id
                host_path = host_mount_dir + str(ckpt_path)[len(docker_outputs):]
            else:
                # Unrecognised structure — skip
                continue

            # ── Metadata: cache hit or full load ─────────────────────────────
            real_path = ckpt_path.resolve()
            real_key  = str(real_path)
            mtime     = int(real_path.stat().st_mtime)

            cached = cache.get(real_key)
            if cached and cached.get("mtime") == mtime:
                obs_dim = cached["obs_dim"]
                epoch   = cached["epoch"]
            else:
                ckpt    = torch.load(str(real_path), map_location="cpu", weights_only=False)
                sd      = ckpt.get("state_dict", {})
                dm      = sd.get("data_mean")
                obs_dim = int(dm.shape[0]) if dm is not None else None
                epoch   = int(ckpt.get("epoch", 0))
                cache[real_key] = {"obs_dim": obs_dim, "epoch": epoch, "mtime": mtime}
                cache_dirty = True

            if obs_dim != target_dim:
                continue

            # ── Dedup: keep highest-priority name per realpath ───────────────
            if real_key not in best or _name_priority(name) < _name_priority(best[real_key][0]):
                best[real_key] = (name, host_path, mtime, epoch)

        except Exception as e:
            print(f"SCAN_ERR {ckpt_path}: {e}", file=sys.stderr)

    # ── Persist updated cache ─────────────────────────────────────────────────
    if cache_dirty:
        try:
            with open(cache_path, "w") as f:
                json.dump(cache, f, indent=2)
        except Exception as e:
            print(f"Cache write error: {e}", file=sys.stderr)

    # ── Emit results ──────────────────────────────────────────────────────────
    for name, host_path, mtime, epoch in best.values():
        model_id = name[len("[eval] "):] if name.startswith("[eval] ") else name
        print(f"{name}|{model_id}|{host_path}|{mtime}|{epoch}")


if __name__ == "__main__":
    main()
